# Generated by Django 2.2.2 on 2019-07-08 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_talkhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 9, 28, 7, 783326)),
        ),
        migrations.AlterField(
            model_name='talkhistory',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 9, 28, 7, 783291)),
        ),
    ]
