# Generated by Django 2.2.2 on 2019-07-08 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190708_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 9, 29, 15, 555071)),
        ),
        migrations.AlterField(
            model_name='talkhistory',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 9, 29, 15, 555034)),
        ),
    ]
