# Generated by Django 2.2.1 on 2019-07-08 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190708_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='talk_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='report_talk_id', to='accounts.TalkHistory'),
        ),
        migrations.AddField(
            model_name='review',
            name='talk_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_talk_id', to='accounts.TalkHistory'),
        ),
        migrations.AlterField(
            model_name='talkhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 16, 17, 21, 224784)),
        ),
        migrations.AlterField(
            model_name='talkhistory',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 8, 16, 17, 21, 224764)),
        ),
    ]
