# Generated by Django 2.2.1 on 2019-07-10 04:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190708_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 10, 11, 22, 4, 819706)),
        ),
        migrations.AlterField(
            model_name='talkhistory',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 10, 11, 22, 4, 819684)),
        ),
        migrations.AlterField(
            model_name='talkhistory',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talk_history2', to=settings.AUTH_USER_MODEL),
        ),
    ]
