# Generated by Django 2.2.1 on 2019-07-10 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190708_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkhistory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='talkhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 10, 11, 37, 51, 58011)),
        ),
        migrations.AlterField(
            model_name='talkhistory',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 10, 11, 37, 51, 57988)),
        ),
    ]
