# Generated by Django 2.2.1 on 2019-07-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190710_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('peerjs_id', models.TextField(default='')),
                ('topic', models.TextField(default='')),
            ],
        ),
    ]
