# Generated by Django 2.2.1 on 2019-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='user',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
