# Generated by Django 2.2.1 on 2019-07-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190724_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=24)),
            ],
        ),
    ]
