# Generated by Django 2.2.1 on 2019-07-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_opentime'),
        ('accounts', '0011_auto_20190727_1304'),
    ]

    operations = [
    ]
