# Generated by Django 2.2.1 on 2019-07-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_conversationstarter_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstarter',
            name='text',
            field=models.CharField(default='', max_length=254),
        ),
    ]
