# Generated by Django 2.1.2 on 2019-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkhistory',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
