# Generated by Django 2.2.2 on 2019-09-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_talkhistory_is_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talkhistory',
            options={'verbose_name_plural': 'Talk Histories'},
        ),
    ]
